basePath: /api/v1
definitions:
  models_v1.CreateBookingIn:
    properties:
      booking_time:
        example: "09:00"
        type: string
      booking_time_period:
        example: 60
        type: integer
      booking_user_id:
        example: 1
        type: integer
      date:
        example: "2024-05-15"
        type: string
      room_id:
        example: 1
        type: integer
      schedule_id:
        example: 1
        type: integer
      service_id:
        example: 1
        type: integer
      store_id:
        example: 1
        type: integer
      user_id:
        example: 1
        type: integer
    required:
    - booking_time
    - booking_time_period
    - booking_user_id
    - date
    - room_id
    - schedule_id
    - service_id
    - store_id
    - user_id
    type: object
  models_v1.CreateServiceIn:
    properties:
      description:
        format: string
        type: string
      name:
        format: string
        type: string
      timePeriod:
        example: 60
        format: integer
        minimum: 1
        type: integer
    required:
    - description
    - name
    - timePeriod
    type: object
  models_v1.GetScheduleOut:
    properties:
      date:
        example: "2024-05-15"
        type: string
      schedule_id:
        description: 返回"2024-05-15"格式的 time.Time 字符串
        example: 1
        type: integer
      stateful_time_slots:
        items:
          $ref: '#/definitions/models_v1.StatefulTimeSlot'
        type: array
      time_period:
        example: 60
        type: integer
    type: object
  models_v1.LoginWeChatIn:
    properties:
      code:
        format: string
        type: string
    required:
    - code
    type: object
  models_v1.QuickGenerateIn:
    properties:
      daily_end_time:
        example: "21:00"
        type: string
      daily_start_time:
        example: "09:00"
        type: string
      generate_days:
        example: 7
        type: integer
      service_id:
        example: 1
        type: integer
      start_date:
        example: "2024-05-15"
        type: string
      user_id:
        example: 1
        type: integer
    required:
    - daily_end_time
    - daily_start_time
    - generate_days
    - service_id
    - start_date
    - user_id
    type: object
  models_v1.StatefulTimeSlot:
    properties:
      is_available:
        example: true
        type: boolean
      time_slot:
        example: "09:00"
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: fuge API
  title: fuge API
  version: "0.1"
paths:
  /appointment:
    post:
      consumes:
      - application/json
      description: 创建预定时间
      parameters:
      - description: 预定日期
        in: body
        name: param
        required: true
        schema:
          $ref: '#/definitions/models_v1.CreateBookingIn'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 创建预定时间
      tags:
      - v1
  /appointment/{id}:
    get:
      consumes:
      - application/json
      description: 通过用户ID获取预定时间
      parameters:
      - description: 用户ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 获取预定时间
      tags:
      - v1
  /booking:
    post:
      consumes:
      - application/json
      description: 创建预定
      parameters:
      - description: 预定日期
        in: body
        name: param
        required: true
        schema:
          $ref: '#/definitions/models_v1.CreateBookingIn'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 创建预定
      tags:
      - v1
      - 预定相关
  /room/store/{storeId}:
    get:
      consumes:
      - application/json
      description: 通过ID获取门店的房间列表
      parameters:
      - description: 门店ID
        in: path
        name: storeId
        required: true
        type: integer
      - description: 用户token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 获取门店的房间列表
      tags:
      - v1
      - 门店相关
  /schedule:
    get:
      consumes:
      - application/json
      description: 获取排班
      parameters:
      - example: "2024-05-15"
        in: query
        name: d
        required: true
        type: string
      - example: 1
        in: query
        name: s
        type: integer
      - example: 1
        in: query
        name: u
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models_v1.GetScheduleOut'
      summary: 获取排班
      tags:
      - v1
      - 排班相关
  /schedule/quick-generate:
    post:
      consumes:
      - application/json
      description: 快速生成排班
      parameters:
      - description: 快速生成排班参数
        in: body
        name: param
        required: true
        schema:
          $ref: '#/definitions/models_v1.QuickGenerateIn'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 快速生成排班
      tags:
      - v1
      - 排班相关
  /user/login-wechat:
    post:
      consumes:
      - application/json
      description: 登陆微信
      parameters:
      - description: 登陆参数
        in: body
        name: param
        required: true
        schema:
          $ref: '#/definitions/models_v1.LoginWeChatIn'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 登陆微信
      tags:
      - v1
  /user/phone-number:
    get:
      consumes:
      - application/json
      description: 获取用户手机号
      parameters:
      - description: 微信code
        in: query
        name: code
        required: true
        type: string
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 获取用户手机号
      tags:
      - v1
  /work:
    post:
      consumes:
      - application/json
      description: 新建工作
      parameters:
      - description: 创建工作内容参数
        in: body
        name: param
        required: true
        schema:
          $ref: '#/definitions/models_v1.CreateServiceIn'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 新建工作
      tags:
      - v1
swagger: "2.0"
