basePath: /api/v1
definitions:
  models_v1.CreateBookingIn:
    properties:
      date:
        format: date
        type: string
      endDateTime:
        format: date-time
        type: string
      startDateTime:
        format: date-time
        type: string
    required:
    - date
    - endDateTime
    - startDateTime
    type: object
  models_v1.CreateServiceIn:
    properties:
      description:
        format: string
        type: string
      name:
        format: string
        type: string
      timePeriod:
        example: 60
        format: integer
        minimum: 1
        type: integer
    required:
    - description
    - name
    - timePeriod
    type: object
host: localhost:8080
info:
  contact: {}
  description: fuge API
  title: fuge API
  version: "0.1"
paths:
  /booking:
    post:
      consumes:
      - application/json
      description: 创建预定时间
      parameters:
      - description: 预定日期
        in: body
        name: param
        required: true
        schema:
          $ref: '#/definitions/models_v1.CreateBookingIn'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 创建预定时间
      tags:
      - v1
  /booking/{id}:
    get:
      consumes:
      - application/json
      description: 通过用户ID获取预定时间
      parameters:
      - description: 用户ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 获取预定时间
      tags:
      - v1
  /example/helloworld:
    get:
      consumes:
      - application/json
      description: do ping
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: ping example
      tags:
      - example
  /serivce:
    post:
      consumes:
      - application/json
      description: 创建服务
      parameters:
      - description: 创建服务参数
        in: body
        name: param
        required: true
        schema:
          $ref: '#/definitions/models_v1.CreateServiceIn'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 创建服务
      tags:
      - v1
swagger: "2.0"
